<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="CPX-85J1I2YMCLF" name="training.Zero.To.Hero.Selenium.ExtentReport_Example" tests="4" failures="0" timestamp="21 Jun 2018 10:04:58 GMT" time="0.151" errors="1">
  <testcase name="demoTestPass" time="0.000" classname="training.Zero.To.Hero.Selenium.ExtentReport_Example">
    <skipped/>
  </testcase> <!-- demoTestPass -->
  <testcase name="demoTestFail" time="0.000" classname="training.Zero.To.Hero.Selenium.ExtentReport_Example">
    <skipped/>
  </testcase> <!-- demoTestFail -->
  <testcase name="startTest" time="0.151" classname="training.Zero.To.Hero.Selenium.ExtentReport_Example">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at training.Zero.To.Hero.Selenium.ExtentReport_Example.startTest(ExtentReport_Example.java:23)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.beforeRun(TestRunner.java:529)
at org.testng.TestRunner.run(TestRunner.java:497)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- startTest -->
  <testcase name="demoTestSkip" time="0.000" classname="training.Zero.To.Hero.Selenium.ExtentReport_Example">
    <skipped/>
  </testcase> <!-- demoTestSkip -->
</testsuite> <!-- training.Zero.To.Hero.Selenium.ExtentReport_Example -->
